export const SET_PLAYER_CHOICE = "SET_PLAYER_CHOICE";
export const SUBMIT_CHOICE = "SUBMIT_CHOICE";
export const RESET_ERROR = "RESET_ERROR";
export const INITIALIZE_GAME = "INITIALIZE_GAME";
export const SUBMIT_COMPUTER_CHOICE = "SUBMIT_COMPUTER_CHOICE";
export const END_GAME = "END_GAME";